#!/usr/bin/python
import socket
import sys
import string

fifo_path="/tmp/cameractl.fifo"



# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Bind the socket to the port
server_address = ('', 10000)
print >>sys.stderr, 'starting up on %s port %s' % server_address
sock.bind(server_address)

# Listen for incoming connections
sock.listen(1)

while True:
    # Wait for a connection
    print >>sys.stderr, 'waiting for a connection'
    connection, client_address = sock.accept()


    try:
        print >>sys.stderr, 'connection from', client_address
        data=''
        # Receive the data in small chunks and retransmit it
        while True:
            # Max length 256 bytes
            data = connection.recv(256)
            if len(data) == 0:
                break
            else:
                print("Got Data: {}".format(data))
                fifo = open(fifo_path, "w")
                fifo.write(data)
                fifo.close()
    finally:
        # Clean up the connection
        connection.close()

